---
title: "mjsalnic_PeerCommentary_cavega_01"
author: "majo"
date: "13/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
title: "cavega_OriginalHomeworkCode_01"
author: "C. Vega"
date: "9/9/2019"
output:
  pdf_document: default
  html_document: default
---
# Matrices and Arrays
library(stringr)
m<- matrix(data=c(1,2,3,4), nrow=2, ncol=2)
m
m<- matrix(data=c(1,2,3,4,5,6), nrow=2, ncol=3, byrow=FALSE)
m
m<- matrix(data=c(1,2,3,4,5,6), nrow=2, ncol=3, byrow=TRUE)
m
v1<- c(1,2,3,4)
v2 <- c(6,7,8,9)
m1 <-rbind(v1,v2)
m1
## Makes into columns (v1 and v2 will be atop each column)
m2 <-cbind(v1,v2)
m2
class(m1)
dim(m1)
class(m2)
dim(m2)
colnames(m2)
rownames(m2)
str(m2)

## Making Arrays
a<- array(data=1:90, dim=c(5,6,3))
a

#Challenge 1 Action

Ulysses<-c("stately","plump","Buck","Mulligan","came","from","the","stairhead","bearing","a","bowl","of","lather","on","which","a","mirror","and","a","razor","lay","crossed")
Ulysses
##Extracting every third element
Ulysses[1:22*3]

#Challenge 2 Practice
m<- matrix(data=1:80, nrow=8, ncol=10, byrow=FALSE)
m
##Extract element and add to new variable
x <- m[4,5]
x
##Extract only row (or only column)
m[row=5,]

#Challenge 2 Action
## ?currently struggling with how to put all three of these into one vector
x<-m[,2],
m[,3], m[,6]

##Figured out how to put all three columns in one vector (Challenge 2.1)
x<-m[,c(2,3,6)]
x

##How to assign rows to a vector (Challenge 2.2)
x<-m[6:8,]
x

##Assign both rows and columns (Challenge 2.3)
x<-m[2:6,2:9]
x

#Challenge 3 Action (a=elements for array)
##Challenge 3.1
a<- array(data=400:1, dim=c(5,5,4,4))
a
##Challenge 3.2
a[1,1,1,2]
### 300
### value of the matrix 1(row),1(col) in matrix 1,2=300
a[2,3,2,]
### 364, 264, 164, 64
a[1:5,1:5,3,3]
### Counts down 150 to 126 by fives
### ? I am curious how this last one works? I understand that the first 1:5 is rows, second 1:5 is columns, but I do not understand the two 3's at the end and how they make the sequence count down in this way.

##it is your matrix 3,3
###, , 3, 3

#     [,1] [,2] [,3] [,4] [,5]
#[1,]  150  145  140  135  130
#[2,]  149  144  139  134  129
#[3,]  148  143  138  133  128
#[4,]  147  142  137  132  127
#[5,]  146  141  136  131  126

#Challenge 4 Practice
##Overwriting 
m[7,1] <- 564
m[,8]<- 2
m[2:5, 4:8] <- 1
m[2:5, 4:8] <- c(20,19,18,17)
m[2:5, 4:8] <- matrix(data = c(20:1, nrow=4, ncol=5,byrow=TRUE))
m[2:5, 4:8]
m[,8]<- c("a", "b")
m[2:5, 4:8]
### ? I am not sure this is right, I kept getting an error saying "# of items to replace is not a multiple of replacement length"
##Lists and Data Frames
###Extracting elements and making a list

### it's because the parentheses are not closed appropriately
### try this
### m[2:5,4:8] <- matrix(data = c(20:1), nrow=4,ncol=5,byrow=TRUE)

s<- c("this","is","a","vector","of","strings")
m <- matrix(data=1:40, nrow=5, ncol=8)
b<- FALSE
l<- list(s,m,b)
l
### ? Why do I keep getting this "subscript out of bounds" error? I looked it up and the internet says it has something to do with looping? 
### Fixed it. I was inputting the number 1 instead of the letter l
l[[2]]
l[[2]][2,6]
l[1:2]
l[c(1,3)]

str(l)

names(l) <- c("string", "matrix", "logical")
names(l)

l$string
l$matrix
l$matrix[3,5]

#Challenge 4 Action
##Challenge 4.1: Make a list of simple primate taxonomy
### ??? I have no idea how to make this bulleted list, i tried nesting the lists but am not sure how to do so
p<- list("primates", "haplorhini", "strepsirhini")

####Read my comment at the end, under your challenges

#Data Frames Practice
##How to Make a Data Frame from Scratch
df<- data.frame(firstName=c("Nitin", "Silvy", "Ingrid", "Claire"), program=c("iSchool", "Anthro", "Anthro", "EEB"), sex=c("M", "F", "F", "F"), yearInProgram=c(1,2,2,3))
df
## Data frame from table- do not need file path if it's in the repo
df <- read.csv("random-people.csv", sep=",", header=TRUE, stringsAsFactors= FALSE)
df

df[,c(1,3,4,11,12)]
str(df)
str(df[,3])
df$name.last
str(df$name.last)
df[3]
df["name.last"]
### ? what is the difference between using str() and df[] or df$name.last? Are they all different ways to do the same thing?

##Adding rows(cases)/columns(variables)
df <- cbind(df, id=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))
df <- cbind(df, school=c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard"))
df

## Directly adding variable
df$school
df$school <- c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard")
df

##Filtering
new_df <-df[df$school == "BU",]
new_df

new_df <-df[df$school == "BU", c("name.last", "name.first", "school")]
new_df


#Challenge 5 Action
##Challenge 5.1: Make Matrix
c<- matrix(data=c(3,0,1,23,1,2,33,1,1,42,0,1,41,0,2), nrow=5, ncol=3, byrow=TRUE)
c
##Challenge 5.2: Make Matrix into data fram
df1<- data.frame(c)
df1
##Challenge 5.3: Coerce to logical-valued and factor-valued
as.logical(df1[,2])
as.factor(df1[,3])

str(df1)

#5 Challenges I Faced
## These are all outlined throughout the document but I will put them all here for ease of understanding.
## 1. When starting out with matrices, I did not understand that you can use combine on whole rows and not just individual data.
## 2. Making an array and understanding what the purpose for stacking them in that way was difficult. I understand the difference between a matrix and array but am confused by what an array is used for.
## 3. The biggest trouble I had with this homework was the lists and specifically how to make the nested primate taxonomy.

##Majo: It was the same for me. In module 4, in the examples/practice part there is a way to do it. I tried, but I'm not sure if is completely accurate.

####From Module 4: Lists are created using the list() function where the elements to add to the list are given as arguments to the function, separated by commas. Type in the following example:

s <- c("this","is","a","vector","of","strings")
m <- matrix(data=1:40, nrow=5, ncol=8) # this is a matrix
b <- FALSE
l <- list(s, m, b)
l

#####You can name the elements in a list using the names() function, which adds a name attribute to each list item.

names(l) <- c("string", "matrix", "logical")
names(l)
## [1] "string"  "matrix"  "logical"

## From this, you could construct a Primates taxonomy list 

Platyrrhini<-c("Cebidae","Atelidae","Pitheciidae")

Catarrhini<-c("Cercopithecidae","Hylobatidae","Hominidae")

Anthropoidea<-list(Platyrrhini,Catarrhini)

names(Anthropoidea)<-c("Platyrrhini","Catarrhini")

Tarsioidea<-c("Tarsiidae")

Haplorhini<-list(Anthropoidea,Tarsioidea)

names(Haplorhini)<-c("Anthropoidea","Tarsioidea")

Lorisoidea<-c("Lorisidae","Galagidae")

Lemuroidea<-c("Cheirogaleidae","Lepilemuridae","Indriidae","Lemuridae","Daubentoniidae")
Strepsirhini<-list(Lorisoidea,Lemuroidea)

names(Strepsirhini)<-c("Lorisoidea","Lemuroidea")

Primates<-list(Haplorhini,Strepsirhini)

names(Primates)<-c("Haplorhini","Strepsirhini")

Primates


## 4. I also wondered what the point of trying out all those different versions of str and df were for. Is it just to show what types of data you have?


##Majo: I think str is just to show you the details about an "object"

## 5. For some of the code if it had not been written out I would have never guessed how to format it, I am nervous that google won't help in the future as much as these early beginner things.

##Peer commentary by Majo

###What you learned from running their code that helped improve your own code.
#I learned to carefuly check each component of the script, a quick view did not show me the "error" but after comparing every element I figured out it was just a missed )
###What you did in your own code that might help to improve theirs.
#I do not believe I'm in the stage to tell anyone how to improve their script based in my own work, but I tried to suggest what seems to work for me
###What challenges, if any, you both faced in your code that could not be helped by comparison.
#I agree with C that may be in the future it could not be easy to solve the trouble by searching in google unless we get a better understanding of how and what we are looking for
###Whether the annotation/commenting on your peer’s code is readable and interpretable to you, and if not then how it could be improved
#It would be good not to include questions (or at least not as questions) in parts that you were able to figure out at the next attempt, that confused me, I was focused on try to answer your question and then I read the next comment saying you figured out. But, I think for the learning process is good to keep those mistakes (as examples) but could be tagged as "problem solved"